apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: lma
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    route:
      routes:
      - match:
        - receiver: "dump"
    receivers:
      - name: "dump"
        elasticsearch:
          hosts:
          - "https://taco-elasticsearch-es-http.lma.svc.skb-suy-prd01.btvpaas.com:9200"
          index: kube-events
          username: elastic
          password: tacoword
          tls: # optional, advanced options for tls
            insecureSkipVerify: true
